version: "3.8"

services:
    master_branch:
      image: kaw393939/mywebclass:master
      container_name: master_branch
      pull_policy: always
      restart: always
      ports:
      - "80:80"
      labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    development_branch:
      image: kaw393939/mywebclass:development
      container_name: development_branch
      pull_policy: always
      restart: always
      ports:
        - "8000:80"
      labels:
        - 'com.centurylinklabs.watchtower.enable=true'
    local_public_html_build:
      build: .
      container_name: local_public_html_build
      restart: always
      ports:
      - "8080:80"
      volumes:
      - ./public_html/:/usr/local/apache2/htdocs/
    local_app_build:
      build: ./app
      container_name: app
      volumes:
        - ./requirements.txt:/home/myuser/requirements.txt
    watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      restart: always
      command: '--interval 30 --label-enable --cleanup'
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      labels:
      - 'com.centurylinklabs.watchtower.enable: true'
